name: .NET

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ dev, release ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SDK_VERSION: 5.0.x
  CI: true
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Debug --no-restore
    - name: Test
      run: dotnet test src --configuration Debug --no-build --no-restore
  publish:
    needs: test
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Restore
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Pack
      run: dotnet pack src --configuration Release --no-build --no-restore
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: ./src/**/*.*nupkg
    - name: Push
      run: dotnet nuget push **/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
